project_id = "zvqzucpwtpjjyeldgaeg"

[functions.openai-chat]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-pro-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.extract-load-data]
verify_jwt = false