// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvqzucpwtpjjyeldgaeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cXp1Y3B3dHBqanllbGRnYWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDUwNDQsImV4cCI6MjA3MDE4MTA0NH0.4CsmF6Mq0N011LqWPmZVPSN8Pk8xfcIQoPbt19Xv_78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});